config/routes.rb
Gistie::Application.routes.draw do

  resources :gists do
    scope format: 'text' do
      match 'blobs/:id/*filename' => 'blobs#show', as: :raw, filename: /.*/, format: false
    end
  end

  root :to => 'gists#index'

end

app/models/gist.rb
class Gist < ActiveRecord::Base

  # TODO: rename this to gist_files instead gist_blobs
  # as blob is just content without filename
  attr_accessor :gist_blobs, :gist_blobs_attributes

  attr_accessible :gist_blobs_attributes, :description

  validate :non_blank, :unique_names

  scope :recent, -> { order('created_at desc') }

  def non_blank
    blank? and errors.add(:gist_blobs, "Can't be blank")
  end

  def unique_names
    dups = dup_names(gist_blobs).map {|name, count| %Q["#{name}": #{count}] }
    dups.empty? or
      errors.add(:gist_blobs, "duplicate names: #{dups.join(',')}")
  end

  def dup_names(blobs)
    duplicates = blobs.map(&:name).
      group_by {|b| b }.
      values.
      map {|b| [b.first, b.size]}.
      select {|name, count| count > 1}
  end

  private :dup_names

  def blank?
    gist_blobs.blank?
  end

  def gist_blobs_attributes
    @gist_blobs_attributes || []
  end

  def gist_blobs_attributes=(attrs)
    self.gist_blobs = attrs.map do |attr|
      GistBlob.new(attr)
    end.reject(&:blank?)
  end

  # Git integration
  def gist_blobs
    @gist_blobs ||= begin
       if new_record? then []
       else gist_read
       end
    end
  end

  def save_and_commit(*args)
    begin
      save_and_commit!(*args) 
      true
    rescue ActiveRecord::RecordInvalid => e
      # TODO: log e
      false
    end
  end

  def save_and_commit!(update_attrs = {})
    SaveGist.new(self).(update_attrs)
  end

  def repo_name
    id.to_s
  end

  def repo
    if new_record? then nil
    else @repo ||= GistRepo.named(repo_name)
    end
  end

  def init_repo
    GistRepo.init_named_repo(repo_name)
  end

  def gist_read
    repo.tree(repo.head).map(&method(:gist_blob))
  end

  def gist_blob(entry)
    # TODO: make consitent
    params = {name: entry.name, blob: entry.content}
    GistBlob.new(params)
  end

  def gist_write
    repo.write(self.gist_blobs)
  end

  def recent_commits(limit = 10)
    repo.log.take(limit)
  end

  def tree(head)
    repo.tree(head || repo.head)
  end

  def to_preview_html
    GistBlobPresenter.new(self.tree(repo.head).first).pretty_excerpt
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  respond_to :html

  def index
    @gists = Gist.recent.page(params[:page])
  end

  def show
    @gist = Gist.find(params[:id])
    @tree = @gist.tree(params[:revision].presence)
  end

  def new
    @gist = Gist.new
  end

  def edit
    @gist = Gist.find(params[:id])
  end

  def create
    @gist = Gist.new(params[:gist])

    if @gist.save_and_commit
      redirect_to @gist, notice: 'Gist was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @gist = Gist.find(params[:id])

    if @gist.save_and_commit(params[:gist])
      redirect_to @gist, notice: 'Gist was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @gist = Gist.find(params[:id])

    @gist.destroy

    redirect_to gists_url, notice: 'Gist was successfully deleted'
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
  <fieldset>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <%# TODO improve error display %>
      <strong><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</strong>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="controls">
      <%= f.text_field 'description', title: 'gist description', placeholder: 'description', class: 'span9 input-xlarge' -%>
    </div>
  </div>

  <hr/>

  <% @gist.gist_blobs.each do |gb| %>
     <%= render partial: 'gist_blob', object: gb, locals: {f: f } %>
  <% end %>

  <% s = 'display:none;' unless @gist.gist_blobs.empty? %>

  <div class="empty" style="<%= s %>">
    <%= render partial: 'gist_blob', object: GistBlob.new, locals: {f: f} %>
  </div>

  <div class="control-group">
    <div class="controls controls-row">
      <span class="span8" style="margin:0">&nbsp</span>
      <span rel="addBlob" class="span1 action act-primary" title="add file"><i class="icon-plus-sign icon-large"></i></span>
    </div>
  </div>

</fieldset>


  <div class="form-actions actions">
    <%= f.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/gists/_gist_blob.html.erb
<% n = "gist[gist_blobs_attributes][]" -%>

<%= f.fields_for(gist_blob) do |gf| -%>

  <div class="control-group file">
    <div class="controls ">
      <div class="controls controls-row"> 
      <%= gf.text_field 'name', :name => "#{n}[name]", class: 'span8' -%>
      <span rel="rmBlob" class="span1 action act-danger" title="remove file"><i class="icon-remove-sign icon-large"></i></span>
      </div>
      <%= gf.text_area 'blob', :name => "#{n}[blob]", class: 'span9' -%>
    </div>
  </div>

<%- end -%>

app/views/gists/_revisions.html.erb
<div class="commits-recent">
  <h4> Revisions </h4>
  <ul class="unstyled">
    <% gist.recent_commits.each do |c| %>
      <li> 
        <a href="<%= gist_path(gist, revision: c.sha) %>"><abbr class="sha" title="<%= c.sha %>"><%= c.pretty_sha %></abbr></a>
        <abbr class="timeago " title="<%= (time = c.created_at.getutc).iso8601 %>"> <%= time.to_s %></abbr>
      </li>
    <% end %>
  </ul>
</div>

app/views/gists/edit.html.erb
<h2><span><%= i('book') %></span>Edit Gist #<%= @gist.id %></h2>

<%= render 'form' %>

app/views/gists/index.html.erb
<h2>Recent gists</h2>

<% if @gists.empty? %>

  be the first to <%= link_to "create one", [:new, :gist] %>

<% else %>

<% @gists.each do |gist| %>

  <div class="row gist" data-gist_id="<%= gist.id %>">
    <div class="span7">
      <h4>
        <%= link_to i('book', "##{gist.id}"), gist %>
        <%= gist.description %> 
      </h4>
    </div>

    <div class="span2">
      <abbr class="timeago pull-right" title="<%= time = gist.created_at.getutc.iso8601 %>"> <%= time.to_s %></abbr>
    </div>

    <div class="span9 syntax">
      <%= gist.to_preview_html %>
    </div>

  </div>
<% end %>

<%= paginate @gists, theme: 'bootstrap', first: false, last: false %>

<% end %>

app/views/gists/new.html.erb
<h2><span><%= i('book') %></span> New gist </h2>


<%= render "form" %>

app/views/gists/show.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'revisions', locals: { gist: @gist } %>
<% end %>

<h2><span><%= i('book') %></span> Gist #<%= @gist.id %></h2>



<div class="row">
  <div class="btn-group span3 pull-right text-pull-right">

    <%= link_to i('edit',  "Edit"), edit_gist_path(@gist), class: 'btn btn-primary' %>

    <button class="btn dropdown-toggle btn-primary" data-toggle="dropdown">
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu">
      <li> <%= link_to i('trash', "Destroy"), @gist,              class: '', method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>

  </div>
</div>

<div class="gist">

  <table class="table table-bordered meta" cellpadding="0" cellspacing="0">
  <tbody>
    <tr class="info">
      <th class="span2"> description </th>
      <td> <%= @gist.description %> </td>
    </tr>
    <tr class="info">
      <th class="span2"> public clone url</th>
      <td> <a href="<%= url = public_clone_url(@gist) %>"> <%= url %> </a> </td>
    </tr>
  </tbody>
  </table>

  <%- @tree.each do |b| %>

    <% gb = GistBlobPresenter.new(b) %>

    <div class="file">
    <div class="row">
      <div class="meta span8"> <%= i('file', b.name) %> </div>
      <div class="meta span1 text-pull-right"> <%= link_to('raw', gist_raw_url(@gist.id, b.oid, b.name)) %> </div>
    </div>
    <div class="data syntax"> <%= gb.pretty_content %> </div>

    </div>

  <% end %>

</div>